// List of all contract names from ponder.config.ts
export const CONTRACT_NAMES = [
  "AAPLon", "ABNBon", "ABTon", "ACNon", "ADBEon", "AGGon", "AMDon", "AMZNon",
  "APOon", "APPon", "ARMon", "ASMLon", "AVGOon", "AXPon", "BABAon", "BAon",
  "BIDUon", "BLKon", "CMGon", "COINon", "COSTon", "CRCLon", "CRMon", "CSCOon",
  "CVXon", "DASHon", "DISon", "EEMon", "EFAon", "EQIXon", "FIGon", "FUTUon",
  "GEon", "GMEon", "GOOGLon", "GSon", "HIMSon", "HOODon", "HYGon", "IAUon",
  "IBMon", "IEFAon", "IEMGon", "IJHon", "INTCon", "INTUon", "ITOTon", "IVVon",
  "IWFon", "IWMon", "IWNon", "JDon", "JPMon", "KOon", "LINon", "LLYon",
  "LMTon", "MAon", "MARAon", "MCDon", "MELIon", "METAon", "MRVLon", "MSFTon",
  "MSTRon", "MUon", "NFLXon", "NKEon", "NOWon", "NVDAon", "NVOon", "ORCLon",
  "PANWon", "PBRon", "PEPon", "PFEon", "PGon", "PLTRon", "PYPLon", "QBTSon",
  "QCOMon", "QQQon", "RDDTon", "RIOTon", "SBETon", "SBUXon", "SHOPon", "SLVon",
  "SMCIon", "SNOWon", "SPGIon", "SPOTon", "SPYon", "TIPon", "TLTon", "TMon",
  "TSLAon", "TSMon", "UBERon", "UNHon", "USDon", "Von", "WFCon", "WMTon",
  "AALon", "ABBVon", "ACHRon", "ADIon", "AMATon", "AMCon", "AMGNon", "ANETon",
  "BACon", "BBAIon", "BILIon", "BINCon", "BLSHon", "BMNRon", "BTGon", "BZon",
  "CATon", "CEGon", "CIFRon", "CLOAon", "CLOIon", "COFon", "Con", "COPon",
  "COPXon", "CPNGon", "CRWDon", "CVNAon", "DBCon", "DEon", "DGRWon", "DNNon",
  "FIGRon", "Fon", "FTGCon", "GEMIon", "GLDon", "GRABon", "GRNDon", "HDon",
  "IRENon", "ISRGon", "JAAAon", "JNJon", "KLACon", "LIon", "LOWon", "LRCXon",
  "MPon", "MRKon", "MRNAon", "MTZon", "NEEon", "NIKLon", "NIOon", "NTESon",
  "OKLOon", "ONDSon", "ONon", "OPENon", "OPRAon", "OSCRon", "OXYon", "PALLon",
  "PCGon", "PDBCon", "PDDon", "PINSon", "PLUGon", "PSQon", "REMXon", "RGTIon",
  "RIVNon", "RTXon", "SCHWon", "SGOVon", "SNAPon", "SOFIon", "SOon", "SOUNon",
  "SQQQon", "TCOMon", "TLNon", "TMOon", "TMUSon", "Ton", "TQQQon", "TXNon",
  "USFRon", "USOon", "VRTon", "VSTon", "VTIon", "VTVon", "VZon", "WULFon",
  "XOMon", "XYZon", "BTGOon",
] as const;
